Use `deploy:deploy` for staging distribution artifacts
`-P deploy` effectively uses `nexus-staging-maven-plugin`. Though
for local deployments it fails as follows:

    [INFO] --- nexus-staging:1.7.0:deploy (default-deploy) @ logging-parent ---
    [INFO] Performing local staging (local stagingDirectory="/home/runner/work/logging-parent/logging-parent/target/nexus-staging/staging")...
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    ...
    [INFO] ------------------------------------------------------------------------
    Error:  Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.7.0:deploy (default-deploy) on project logging-parent: Execution default-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.7.0:deploy failed: Cannot decipher credentials to be used with Nexus! org.sonatype.plexus.components.sec.dispatcher.shaded.SecDispatcherException: java.io.FileNotFoundException: /home/runner/.m2/settings-security.xml (No such file or directory)

Hence, explicitly opting for `maven-deploy-plugin:deploy` which
doesn't suffer from this problem.